fix: actualización del pipeline de Terraform y Datadog

diff --git a/.github/workflows/terraform-datadog-pipeline.yml b/.github/workflows/terraform-datadog-pipeline.yml
--- a/.github/workflows/terraform-datadog-pipeline.yml
+++ b/.github/workflows/terraform-datadog-pipeline.yml
@@ -46,7 +46,7 @@ jobs:
          terraform init
          terraform fmt -check
          terraform validate
-         terraform plan -out=tfplan || terraform show -json tfplan.error
+         terraform plan -out=tfplan || (echo "Terraform plan failed. Please inspect the issue." && exit 1)
       
       - name: Terraform Apply
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
@@ -69,8 +69,7 @@ jobs:
         run: |
           FRONTEND_IP=$(jq -r .frontend_public_ip.value < ./tf/outputs.json)
           BACKEND_IP=$(jq -r .backend_public_ip.value < ./tf/outputs.json)
-          echo "EC2_INSTANCE=frontend_public_ip=$FRONTEND_IP,backend_public_ip=$BACKEND_IP" > .env
-          gh secret set EC2_INSTANCE -b"$(cat .env)"
+          echo "EC2_INSTANCE=frontend_public_ip=$FRONTEND_IP,backend_public_ip=$BACKEND_IP" >> $GITHUB_ENV
 
   deploy_agent:
     name: Despliegue del Agente Datadog
@@ -100,5 +99,4 @@ jobs:
           ssh ec2 '
             chmod +x ~/install_datadog_agent.sh
             sudo DD_API_KEY=${{ secrets.DATADOG_API_KEY }} ~/install_datadog_agent.sh
-            rm ~/install_datadog_agent.sh
-          ' 
+            rm ~/install_datadog_agent.sh 
